version: "3.7"

services:
  app:
    image: vanbui1995/node-multiple:latest
    command: ["./devops/scripts/wait-for-it.sh", "mysql:3306", "--", "node", "/app/src/index.js"]
    ports:
      - 3000
    environment:
      SQL_HOST: mysql
      SQL_USERNAME: root
      SQL_PASSWORD: my-secret-pw
      SQL_DATABASE: vanbui
    depends_on:
      - mysql
    deploy:
      replicas: 3



  mysql:
    ports:
      - 3306:3306
    image: arm64v8/mysql:8.0.29-oracle
    volumes:
      - vanbui:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw

  nginx:
    image: nginx:latest
    volumes:
      - ./devops/configs/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    ports:
      - "80:4000"

volumes:
  vanbui: